namespace TwilightImperiumUltimate.Contracts.Enums;

public enum ActionCardName
{
    AncientBurialSites,
    ArchaeologicalExpedition,
    AssassinateRepresentative,
    Blitz,
    Bribery, // Errata
    Bunker,
    ConfoundingLegalText,
    ConfusingLegalText,
    ConstructionRider,
    Counterstroke,
    CoupDetat,
    CourageousToTheEnd,
    CrippleDefenses,
    DeadlyPlot,
    DecoyOperation,
    DiplomacyRider,
    DiplomaticPressure, // 4x
    DirectHit, // Errata + 4x
    Disable,
    DistinguishedCouncilor,
    DivertFunding,
    EconomicInitiative,
    EmergencyRepairs,
    ExperimentalBattlestation,
    ExplorationProbe,
    FighterConscription,
    FighterPrototype,
    FireTeam,
    FlankSpeed, // 4x
    FocusedResearch,
    ForwardSupplyBase,
    FrontlineDeployment,
    GhostShip,
    GhostSquad,
    HackElection,
    HarnessEnergy,
    ImperialRider,
    Impersonation,
    InTheSilenceOfSpace,
    IndustrialInitiative,
    Infiltrate,
    InsiderInformation,
    Insubordination,
    Intercept,
    LeadershipRider,
    LostStarChart,
    LuckyShot,
    ManeuveringJets, // 4x
    ManipulateInvestments,
    MasterPlan,
    MiningInitiative,
    MoraleBoost, // 4x
    NavSuite,
    Parley,
    Plagiarize,
    Plague,
    PoliticalStability,
    PoliticsRider,
    PublicDisgrace,
    Rally,
    ReactorMeltdown,
    RefitTroops,
    ReflectiveShielding,
    Reparations,
    RepealLaw,
    RevealPrototype,
    ReverseEngineer,
    RiseOfAMessiah,
    Rout,
    Sabotage, // 4x
    Salvage,
    Sanction,
    ScrambleFrequency,
    Scuttle,
    SeizeArtifact,
    ShieldsHolding, // 4x
    SignalJamming,
    SkilledRetreat, // 4x
    SolarFlare,
    Spy,
    Summit,
    TacticalBombardment,
    TechnologyRider,
    TradeRider,
    UnexpectedAction,
    UnstablePlanet, // Errata
    Upgrade,
    Uprising,
    Veto, // Errata
    WarEffort,
    WarMachine, // 4x
    WarfareRider,
    Waylay,

    AbyssalStarpaths,
    AggressiveBroker,
    AIAugury,
    Arbitrage,
    BountyContracts,
    CarapacePlating,
    ClassifiedWeapons,
    ConfusedSage,
    Contagion,
    EchoShielding,
    EmergencyMeeting,
    EscapeClause,
    ForbiddenKnowledge,
    FreeTradeInitiative,
    FreedomFighters,
    FulfillmentProtocols,
    HostileWorld,
    IllusoryDuplication,
    MicrometeoroidSwarm,
    NeuralHammer,
    PersonnelWrit,
    PlanetaryRigs,
    Preparation,
    ProfessionalArchaeologists,
    RemnantCollection,
    Renegotiation,
    SafetyOverrides,
    SecuredTrove,
    SingularityCharge,
    SpecialSession,

    BlackMarketDealings,
    Brilliance,
    CrashLanding,
    Crisis,
    ExchangeProgram,
    ExtremeDuress,
    LieInWait,
    MercenaryContract,
    PirateContract,
    PirateFleet,
    PuppetsOnAString,
    Rescue,
    Strategize,
    Overrule,
}
