namespace TwilightImperiumUltimate.Contracts.Enums;

public enum AsyncFactionName
{
    // Base game - 17 factions
    TheArborec,
    TheBaronyOfLetnev,
    TheClanOfSaar,
    TheEmbersOfMuaat,
    TheEmiratesOfHacan,
    TheFederationOfSol,
    TheGhostsOfCreuss,
    TheL1z1xMindnet,
    TheMentakCoalition,
    TheNaaluCollective,
    TheNekroVirus,
    SardakkNorr,
    TheUniversitiesOfJolNar,
    TheWinnu,
    TheXxchaKingdom,
    TheYinBrotherhood,
    TheYssarilTribes,

    // Prophecy of Kings - 7 factions
    TheArgentFlight,
    TheEmpyrean,
    TheMahactGeneSorcerers,
    TheNaazRokhaAlliance,
    TheNomad,
    TheTitansOfUl,
    TheVuilRaithCabal,

    // Keleres
    TheCouncilKeleresMentak,
    TheCouncilKeleresXxcha,
    TheCouncilKeleresArgent,

    // Discordant Stars - 34 factions
    TheAugursOfIlyxum,
    TheBentorConglomerate,
    TheBerserkersOfKjalengard,
    TheCeldauriTradeConfederation,
    TheCheiranHordes,
    TheDihMohnFlotilla,
    TheEdynMandate,
    TheFlorzenProfiteers,
    TheFreeSystemsCompact,
    TheGheminaRaiders,
    TheGhotiWayfarers,
    TheGledgeUnion,
    TheGlimmerOfMortheus,
    TheKolleccSociety,
    TheKortaliTribunal,
    TheKyroSodality,
    TheLanefirRemnants,
    TheLiZhoDynasty,
    TheLTokkKhrask,
    TheMirvedaProtectorate,
    TheMonksOfKolume,
    TheMykoMentori,
    TheNivynStarKings,
    TheNokarSellships,
    TheOlradinLeague,
    RohDhnaMechatronics,
    TheSavagesOfCymiae,
    TheShipwrightsofAxis,
    TheTnelisSyndicate,
    TheVadenBankingClans,
    TheVaylerianScourge,
    TheVeldyrSovereignty,
    TheZealotsOfRhodun,
    TheZelianPurifier,

    // Other
    Franken,
    Homebrew,
}
