namespace TwilightImperiumUltimate.Contracts.Enums;

public enum MapTemplate
{
    CustomMap,
    ThreePlayersSmallMap,
    ThreePlayersSmallAlternateMap,
    ThreePlayersTriangleMap,
    ThreePlayersTriangleNarrowMap,
    ThreePlayersSnowflakeMap,
    ThreePlayersMantaRayMap,
    FourPlayersMediumMap,
    FourPlayersMediumHorizontalMap,
    FourPlayersMediumVerticalMap,
    FourPlayersMediumGapsMap,
    FourPlayersMediumWarpMap,
    FourPlayersMediumMiniWarpMap,
    FourPlayersMediumDoubleWarpMap,
    FivePlayersMediumMap,
    FivePlayersMediumHyperlineMap,
    FivePlayersMediumDiamondMap,
    FivePlayersLargeFlatMap,
    SixPlayersMediumMap,
    SixPlayersMediumSpiralMap,
    SixPlayersLargeMap,
    SevenPlayersLargeHyperlineMap,
    SevenPlayersLargeWarpMap,
    EightPlayersLargeMap,
    EightPlayersLargeWarpMap,
}
