namespace TwilightImperiumUltimate.Contracts.Enums;

public enum MapTemplate
{
    CustomMap,
    TwoPlayersMediumMap,
    ThreePlayersSmallMap,
    ThreePlayersSmallAlternateMap,
    ThreePlayersMediumTriangleMap,
    ThreePlayersMediumTriangleNarrowMap,
    ThreePlayersMediumSnowflakeMap,
    ThreePlayersMediumMantaRayMap,
    ThreePlayersMediumTridentMap,
    ThreePlayersMediumRexMap,
    FourPlayersMediumMap,
    FourPlayersMediumHorizontalMap,
    FourPlayersMediumVerticalMap,
    FourPlayersMediumGapsMap,
    FourPlayersMediumWarpMap,
    FourPlayersMediumMiniWarpMap,
    FourPlayersMediumDoubleWarpMap,
    FivePlayersMediumMap,
    FivePlayersMediumHyperlineMap,
    FivePlayersMediumDiamondMap,
    FivePlayersLargeFlatMap,
    SixPlayersMediumMap,
    SixPlayersMediumSpiralMap,
    SixPlayersLargeMap,
    SevenPlayersLargeHyperlineMap,
    SevenPlayersLargeWarpMap,
    EightPlayersLargeMap,
    EightPlayersLargeWarpMap,
}
