namespace TwilightImperiumUltimate.Contracts.Enums;

public enum TechnologyName
{
    // Base technolgoies
    NeuralMotivator,
    Psychoarchaeology,
    DacxiveAnimators,
    BioStims,
    HyperMetabolism,
    X89BacterialWeapon,
    X89BacterialWeaponOmega,
    AntimassDeflectors,
    DarkEnergyTap,
    GravityDrive,
    SlingRelay,
    FleetLogistics,
    LightWaveDeflector,
    SarweenTools,
    ScanlinkDroneNetwork,
    GravitonLaserSystem,
    PredictiveIntelligence,
    TransitDiodes,
    IntegratedEconomy,
    PlasmaScoring,
    AIDevelopmentAlgorithm,
    MagenDefenseGrid,
    MagenDefenseGridOmega,
    SelfAssemblyRoutines,
    DuraniumArmor,
    AssaultCannon,

    // Unit upgrade technologies
    InfantryTwo,
    FighterTwo,
    DestroyerTwo,
    CarrierTwo,
    CruiserTwo,
    DreadnoughtTwo,
    WarSun,
    SpaceDockTwo,
    PdsTwo,

    // Faction technologies
    LetaniWarrior,
    Bioplasmosis,
    L4Disruptors,
    NonEuclidianShielding,
    FloatingFactory,
    ChaosMapping,
    PrototypeWarSun,
    MagmusReactor,
    MagmusReactorOmega,
    ProductionBiomes,
    QuantumDatahubNode,
    SpecOps,
    AdvancedCarrier,
    WormholeGenerator,
    WormholeGeneratorOmega,
    DimensionalSplicer,
    SuperDreadnought,
    InheritanceSystems,
    SalvageOperations,
    MirrorComputing,
    HybridCrystalFighter,
    Neuroglaive,
    ValefarAssimilatorX,
    ValefarAssimilatorY,
    Exotrireme,
    WalkyrieParticleWeave,
    EResSiphons,
    SpacialConduitCylinder,
    LazaxGateFolding,
    HegemonicTradePolicy,
    NullificationField,
    InstrinctTraining,
    ImpulseCore,
    YinSpinner,
    YinSpinnerOmega,
    TransparasteelPlating,
    MageonImplants,
    StrikeWingAlpha,
    AerieHololattice,
    Aetherstream,
    Voidwatch,
    CrimsonLegionnaire,
    GeneticRecombination,
    Supercharge,
    PreFabArcologies,
    Memoria,
    TemporalCommandSuite,
    SaturnEngine,
    HelTitan,
    DimensionalTear,
    Vortex,
    IihqModernization,
    AgencySupplyNetwork,

    Psychographics,
    SentientDatapool,
    EmergencyMobilizationProtocols,
    TradePortTwo, // F
    ImpressmentPrograms,
    AegisTwo, // F
    BlackmailPrograms,
    CorsairTwo, // F
    EnvoyNetwork,
    CovertStrikeTeams,
    WarSongImplants,
    CombatTransportTwo, // F
    FractalPlating,
    FabricationGrid,
    SeekerDrones,
    ShroudedSkirmishers,
    TempestDrive,
    DeliveranceEngine,
    WraithEngine,
    HeavyBomberTwo, // F
    StonesEmbrace,
    ShatteredSkyTwo, // F
    OrbitalDefenseGrid,
    GaussCannonTwo, // F
    PsychoactiveArmaments,
    MyceliumRingTwo, // F
    VoidwakeMissiles,
    VoidflareWardenTwo, // F
    FalseFlagOperations,
    GeosympathicImpeller,
    ContractualObligations,
    TerrafactoryTwo, // F
    RecursiveWorm,
    UnholyAbominationTwo, // F
    RiftEngines,
    EmergencyDeployment,
    DaedalonFlightSystem,
    BlockadeRunnerTwo, // F
    MidasTurbine,
    KrovozStrikeTeams,
    ScavengerExos,
    RaiderTwo, // F
    SeidrProject,
    LancerDreadnoughtTwo, // F
    SanctificationField,
    PilgrimageBeacons,
    ShardVolley,
    ImpactorTwo, // F
    BrokerNetwork,
    MergedReplicators,
    BroodPod,
    ChitinHulkTwo, // F
    UnityAlgorithm,
    EncryptedTradeHub,
    NetworkedCommand,
    ParallelProduction,
    LightningDrives,
    OrionPlatformTwo,
    ZhrgarStimulants,
    StarDragonTwo, // F
    AppliedBiothermics,
    OmniscienceField,
    IndoctrinationTeam,
    VectorProgram,
    SparkThrusters,
    AtsArmaments,
    LocalContracts,
    SabreTwo, // F
}
