namespace TwilightImperiumUltimate.Business.Helpers;

public static class AsyncFactionParser
{
    public static AsyncFactionName ParseFaction(string faction)
    {
        return faction switch
        {
            "The Arborec" => AsyncFactionName.TheArborec,
            "The Barony of Letnev" => AsyncFactionName.TheBaronyOfLetnev,
            "The Clan of Saar" => AsyncFactionName.TheClanOfSaar,
            "The Embers of Muaat" => AsyncFactionName.TheEmbersOfMuaat,
            "The Emirates of Hacan" => AsyncFactionName.TheEmiratesOfHacan,
            "The Federation of Sol" => AsyncFactionName.TheFederationOfSol,
            "The Ghosts of Creuss" => AsyncFactionName.TheGhostsOfCreuss,
            "The L1Z1X Mindnet" => AsyncFactionName.TheL1z1xMindnet,
            "The Mentak Coalition" => AsyncFactionName.TheMentakCoalition,
            "The Naalu Collective" => AsyncFactionName.TheNaaluCollective,
            "The Nekro Virus" => AsyncFactionName.TheNekroVirus,
            "Sardakk Norr" => AsyncFactionName.SardakkNorr,
            "The Universities of Jol-Nar" => AsyncFactionName.TheUniversitiesOfJolNar,
            "The Winnu" => AsyncFactionName.TheWinnu,
            "The Xxcha Kingdom" => AsyncFactionName.TheXxchaKingdom,
            "The Yin Brotherhood" => AsyncFactionName.TheYinBrotherhood,
            "The Yssaril Tribes" => AsyncFactionName.TheYssarilTribes,

            "The Argent Flight" => AsyncFactionName.TheArgentFlight,
            "The Empyrean" => AsyncFactionName.TheEmpyrean,
            "The Mahact Gene-Sorcerers" => AsyncFactionName.TheMahactGeneSorcerers,
            "The Naaz-Rokha Alliance" => AsyncFactionName.TheNaazRokhaAlliance,
            "The Nomad" => AsyncFactionName.TheNomad,
            "The Titans of Ul" => AsyncFactionName.TheTitansOfUl,
            "The Vuil'raith Cabal" => AsyncFactionName.TheVuilRaithCabal,

            "The Council Keleres - Mentak" => AsyncFactionName.TheCouncilKeleresMentak,
            "The Council Keleres - Xxcha" => AsyncFactionName.TheCouncilKeleresXxcha,
            "The Council Keleres - Argent" => AsyncFactionName.TheCouncilKeleresArgent,

            "The Crimson Rebellion" => AsyncFactionName.TheCrimsonRebellion,
            "The Deepwrought Scholarate" => AsyncFactionName.TheDeepwroughtScholarate,
            "The Firmament" => AsyncFactionName.TheFirmamentTheObsidian,
            "The Obsidian" => AsyncFactionName.TheFirmamentTheObsidian,
            "Last Bastion" => AsyncFactionName.LastBastion,
            "The Ral Nel Consortium" => AsyncFactionName.TheRalNelConsortium,

            "The Ruby Monarch" => AsyncFactionName.TheRubyMonarch,
            "Radiant Aur" => AsyncFactionName.RadiantAur,
            "Avarice Rex" => AsyncFactionName.AvariceRex,
            "Il Sai Lakoe, Herald of Thorns" => AsyncFactionName.IlSaiLakoeHeraldOfThorns,
            "The Saint of Swords" => AsyncFactionName.TheSaintOfSwords,
            "Il Na Viroset" => AsyncFactionName.IlNaViroset,
            "El Nen Janovet" => AsyncFactionName.ElNenJanovet,
            "A Sickening Lurch" => AsyncFactionName.ASickeningLurch,

            "Augers of Ilyxum" => AsyncFactionName.TheAugursOfIlyxum,
            "Celdauri Trade Confederation" => AsyncFactionName.TheCeldauriTradeConfederation,
            "Dih-Mohn Flotilla" => AsyncFactionName.TheDihMohnFlotilla,
            "Florzen Profiteers" => AsyncFactionName.TheFlorzenProfiteers,
            "Free Systems Compact" => AsyncFactionName.TheFreeSystemsCompact,
            "Ghemina Raiders" => AsyncFactionName.TheGheminaRaiders,
            "Glimmer of Mortheus" => AsyncFactionName.TheGlimmerOfMortheus,
            "Kollecc Society" => AsyncFactionName.TheKolleccSociety,
            "Kortali Tribunal" => AsyncFactionName.TheKortaliTribunal,
            "Li-Zho Dynasty" => AsyncFactionName.TheLiZhoDynasty,
            "L'Tokk Khrask" => AsyncFactionName.TheLTokkKhrask,
            "Mirveda Protectorate" => AsyncFactionName.TheMirvedaProtectorate,
            "Myko-Mentori" => AsyncFactionName.TheMykoMentori,
            "Nivyn Star Kings" => AsyncFactionName.TheNivynStarKings,
            "Olradin League" => AsyncFactionName.TheOlradinLeague,
            "Roh'Dhna Mechatronics" => AsyncFactionName.RohDhnaMechatronics,
            "Savages of Cymiae" => AsyncFactionName.TheSavagesOfCymiae,
            "Shipwrights of Axis" => AsyncFactionName.TheShipwrightsofAxis,
            "Tnelis Syndicate" => AsyncFactionName.TheTnelisSyndicate,
            "Vaden Banking Clans" => AsyncFactionName.TheVadenBankingClans,
            "Vaylerian Scourge" => AsyncFactionName.TheVaylerianScourge,
            "Veldyr Sovereignty" => AsyncFactionName.TheVeldyrSovereignty,
            "Zealots of Rhodun" => AsyncFactionName.TheZealotsOfRhodun,
            "Zelian Purifier" => AsyncFactionName.TheZelianPurifier,
            "Bentor Conglomerate" => AsyncFactionName.TheBentorConglomerate,
            "Cheiran Hordes" => AsyncFactionName.TheCheiranHordes,
            "Edyn Mandate" => AsyncFactionName.TheEdynMandate,
            "Ghoti Wayfarers" => AsyncFactionName.TheGhotiWayfarers,
            "Gledge Union" => AsyncFactionName.TheGledgeUnion,
            "Berserkers of Kjalengard" => AsyncFactionName.TheBerserkersOfKjalengard,
            "Monks of Kolume" => AsyncFactionName.TheMonksOfKolume,
            "Kyro Sodality" => AsyncFactionName.TheKyroSodality,
            "Lanefir Remnants" => AsyncFactionName.TheLanefirRemnants,
            "Nokar Sellships" => AsyncFactionName.TheNokarSellships,

            "Uydai Conclave" => AsyncFactionName.UydaiConclave,
            "Pharadn Order" => AsyncFactionName.PharadnOrder,
            "Qhet Republic" => AsyncFactionName.QhetRepublic,
            "Atokera Legacy" => AsyncFactionName.AtokeraLegacy,
            "Belkosea Allied States" => AsyncFactionName.BelkoseaAlliedStates,
            "Toldar Concordat" => AsyncFactionName.ToldarConcordat,

            "Franken 1" => AsyncFactionName.Franken,
            "Franken 2" => AsyncFactionName.Franken,
            "Franken 3" => AsyncFactionName.Franken,
            "Franken 4" => AsyncFactionName.Franken,
            "Franken 5" => AsyncFactionName.Franken,
            "Franken 6" => AsyncFactionName.Franken,
            "Franken 7" => AsyncFactionName.Franken,
            "Franken 8" => AsyncFactionName.Franken,
            "Franken 9" => AsyncFactionName.Franken,
            "Franken 10" => AsyncFactionName.Franken,
            "Franken 11" => AsyncFactionName.Franken,
            "Franken 12" => AsyncFactionName.Franken,
            "Franken 13" => AsyncFactionName.Franken,
            "Franken 14" => AsyncFactionName.Franken,
            "Franken 15" => AsyncFactionName.Franken,
            "Franken 16" => AsyncFactionName.Franken,
            "Franken 17" => AsyncFactionName.Franken,
            "Franken 18" => AsyncFactionName.Franken,
            "Franken 19" => AsyncFactionName.Franken,
            "Franken 20" => AsyncFactionName.Franken,
            "Franken 21" => AsyncFactionName.Franken,
            "Franken 22" => AsyncFactionName.Franken,
            "Franken 23" => AsyncFactionName.Franken,
            "Franken 24" => AsyncFactionName.Franken,
            "Franken 25" => AsyncFactionName.Franken,
            "Franken 26" => AsyncFactionName.Franken,

            _ => AsyncFactionName.Unknown,
        };
    }
}
