//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilightImperiumUltimate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilightImperiumUltimate.Web.Resources.CardNames", typeof(CardNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieve Supremacy.
        /// </summary>
        internal static string ObjectiveCardName_AchieveSupremacy {
            get {
                return ResourceManager.GetString("ObjectiveCardName_AchieveSupremacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapt New Strategies.
        /// </summary>
        internal static string ObjectiveCardName_AdaptNewStrategies {
            get {
                return ResourceManager.GetString("ObjectiveCardName_AdaptNewStrategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Mass Wealth.
        /// </summary>
        internal static string ObjectiveCardName_AMassWealth {
            get {
                return ResourceManager.GetString("ObjectiveCardName_AMassWealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become A Legend.
        /// </summary>
        internal static string ObjectiveCardName_BecomeALegend {
            get {
                return ResourceManager.GetString("ObjectiveCardName_BecomeALegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become A Martyr.
        /// </summary>
        internal static string ObjectiveCardName_BecomeAMartyr {
            get {
                return ResourceManager.GetString("ObjectiveCardName_BecomeAMartyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become The Gatekeeper.
        /// </summary>
        internal static string ObjectiveCardName_BecomeTheGatekeeper {
            get {
                return ResourceManager.GetString("ObjectiveCardName_BecomeTheGatekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betray A Friend.
        /// </summary>
        internal static string ObjectiveCardName_BetrayAFriend {
            get {
                return ResourceManager.GetString("ObjectiveCardName_BetrayAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brave The Void.
        /// </summary>
        internal static string ObjectiveCardName_BraveTheVoid {
            get {
                return ResourceManager.GetString("ObjectiveCardName_BraveTheVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Defenses.
        /// </summary>
        internal static string ObjectiveCardName_BuildDefenses {
            get {
                return ResourceManager.GetString("ObjectiveCardName_BuildDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralize Galactic Trade.
        /// </summary>
        internal static string ObjectiveCardName_CentralizeGalacticTrade {
            get {
                return ResourceManager.GetString("ObjectiveCardName_CentralizeGalacticTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command An Armada.
        /// </summary>
        internal static string ObjectiveCardName_CommandAnArmada {
            get {
                return ResourceManager.GetString("ObjectiveCardName_CommandAnArmada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conquer The Weak.
        /// </summary>
        internal static string ObjectiveCardName_ConquerTheWeak {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ConquerTheWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct Massive Cities.
        /// </summary>
        internal static string ObjectiveCardName_ConstructMassiveCities {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ConstructMassiveCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control The Borderlands.
        /// </summary>
        internal static string ObjectiveCardName_ControlTheBorderlands {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ControlTheBorderlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control The Region.
        /// </summary>
        internal static string ObjectiveCardName_ControlTheRegion {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ControlTheRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner The Market.
        /// </summary>
        internal static string ObjectiveCardName_CornerTheMarket {
            get {
                return ResourceManager.GetString("ObjectiveCardName_CornerTheMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Supply Lines.
        /// </summary>
        internal static string ObjectiveCardName_CutSupplyLines {
            get {
                return ResourceManager.GetString("ObjectiveCardName_CutSupplyLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darken The Skies.
        /// </summary>
        internal static string ObjectiveCardName_DarkenTheSkies {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DarkenTheSkies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defy Space And Time.
        /// </summary>
        internal static string ObjectiveCardName_DefySpaceAndTime {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DefySpaceAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate Your Power.
        /// </summary>
        internal static string ObjectiveCardName_DemonstrateYourPower {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DemonstrateYourPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Heretical Works.
        /// </summary>
        internal static string ObjectiveCardName_DestroyHereticalWorks {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DestroyHereticalWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Their Greatest Ship.
        /// </summary>
        internal static string ObjectiveCardName_DestroyTheirGreatestShip {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DestroyTheirGreatestShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop Weaponry.
        /// </summary>
        internal static string ObjectiveCardName_DevelopWeaponry {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DevelopWeaponry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictate Policy.
        /// </summary>
        internal static string ObjectiveCardName_DictatePolicy {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DictatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover Lost Outposts.
        /// </summary>
        internal static string ObjectiveCardName_DiscoverLostOutposts {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DiscoverLostOutposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversify Research.
        /// </summary>
        internal static string ObjectiveCardName_DiversifyResearch {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DiversifyResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive The Debate.
        /// </summary>
        internal static string ObjectiveCardName_DriveTheDebate {
            get {
                return ResourceManager.GetString("ObjectiveCardName_DriveTheDebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer A Marvel.
        /// </summary>
        internal static string ObjectiveCardName_EngineerAMarvel {
            get {
                return ResourceManager.GetString("ObjectiveCardName_EngineerAMarvel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erect A Monument.
        /// </summary>
        internal static string ObjectiveCardName_ErectAMonument {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ErectAMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish A Perimeter.
        /// </summary>
        internal static string ObjectiveCardName_EstablishAPerimeter {
            get {
                return ResourceManager.GetString("ObjectiveCardName_EstablishAPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish Hegemony.
        /// </summary>
        internal static string ObjectiveCardName_EstablishHegemony {
            get {
                return ResourceManager.GetString("ObjectiveCardName_EstablishHegemony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Borders.
        /// </summary>
        internal static string ObjectiveCardName_ExpandBorders {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ExpandBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Deep Space.
        /// </summary>
        internal static string ObjectiveCardName_ExploreDeepSpace {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ExploreDeepSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight With Precision.
        /// </summary>
        internal static string ObjectiveCardName_FightWithPrecision {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FightWithPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight With Precision  Ω.
        /// </summary>
        internal static string ObjectiveCardName_FightWithPrecisionOmega {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FightWithPrecisionOmega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge An Alliance.
        /// </summary>
        internal static string ObjectiveCardName_ForgeAnAlliance {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ForgeAnAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form A Spy Network.
        /// </summary>
        internal static string ObjectiveCardName_FormASpyNetwork {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FormASpyNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Galactic Brain Trust.
        /// </summary>
        internal static string ObjectiveCardName_FormGalacticBrainTrust {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FormGalacticBrainTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foster Cohesion.
        /// </summary>
        internal static string ObjectiveCardName_FosterCohesion {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FosterCohesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found A Golden Age.
        /// </summary>
        internal static string ObjectiveCardName_FoundAGoldenAge {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FoundAGoldenAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Research Outposts.
        /// </summary>
        internal static string ObjectiveCardName_FoundResearchOutposts {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FoundResearchOutposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel The War Machine.
        /// </summary>
        internal static string ObjectiveCardName_FuelTheWarMachine {
            get {
                return ResourceManager.GetString("ObjectiveCardName_FuelTheWarMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galvanize The People.
        /// </summary>
        internal static string ObjectiveCardName_GalvanizeThePeople {
            get {
                return ResourceManager.GetString("ObjectiveCardName_GalvanizeThePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather A Mighty Fleet.
        /// </summary>
        internal static string ObjectiveCardName_GatherAMightyFleet {
            get {
                return ResourceManager.GetString("ObjectiveCardName_GatherAMightyFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoard Raw Materials.
        /// </summary>
        internal static string ObjectiveCardName_HoardRawMaterials {
            get {
                return ResourceManager.GetString("ObjectiveCardName_HoardRawMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Vast Reserves.
        /// </summary>
        internal static string ObjectiveCardName_HoldVastReserves {
            get {
                return ResourceManager.GetString("ObjectiveCardName_HoldVastReserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve Infrastructure.
        /// </summary>
        internal static string ObjectiveCardName_ImproveInfrastructure {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ImproveInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidate Council.
        /// </summary>
        internal static string ObjectiveCardName_IntimidateCouncil {
            get {
                return ResourceManager.GetString("ObjectiveCardName_IntimidateCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead From The Front.
        /// </summary>
        internal static string ObjectiveCardName_LeadFromTheFront {
            get {
                return ResourceManager.GetString("ObjectiveCardName_LeadFromTheFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn The Secrets Of The Cosmos.
        /// </summary>
        internal static string ObjectiveCardName_LearnTheSecretsOfTheCosmos {
            get {
                return ResourceManager.GetString("ObjectiveCardName_LearnTheSecretsOfTheCosmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make An Example Of Their World.
        /// </summary>
        internal static string ObjectiveCardName_MakeAnExampleOfTheirWorld {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MakeAnExampleOfTheirWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make An Example Of Their World  Ω.
        /// </summary>
        internal static string ObjectiveCardName_MakeAnExampleOfTheirWorldOmega {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MakeAnExampleOfTheirWorldOmega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make History.
        /// </summary>
        internal static string ObjectiveCardName_MakeHistory {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MakeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulate Galactic Law.
        /// </summary>
        internal static string ObjectiveCardName_ManipulateGalacticLaw {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ManipulateGalacticLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master The Laws Of Physics.
        /// </summary>
        internal static string ObjectiveCardName_MasterTheLawsOfPhysics {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MasterTheLawsOfPhysics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master The Sciences.
        /// </summary>
        internal static string ObjectiveCardName_MasterTheSciences {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MasterTheSciences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanize The Military.
        /// </summary>
        internal static string ObjectiveCardName_MechanizeTheMilitary {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MechanizeTheMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Rare Minerals.
        /// </summary>
        internal static string ObjectiveCardName_MineRareMinerals {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MineRareMinerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monopolize Production.
        /// </summary>
        internal static string ObjectiveCardName_MonopolizeProduction {
            get {
                return ResourceManager.GetString("ObjectiveCardName_MonopolizeProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiate Trade Routes.
        /// </summary>
        internal static string ObjectiveCardName_NegotiateTradeRoutes {
            get {
                return ResourceManager.GetString("ObjectiveCardName_NegotiateTradeRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupy The Fringe.
        /// </summary>
        internal static string ObjectiveCardName_OccupyTheFringe {
            get {
                return ResourceManager.GetString("ObjectiveCardName_OccupyTheFringe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupy The Seat Of The Empire.
        /// </summary>
        internal static string ObjectiveCardName_OccupyTheSeatOfTheEmpire {
            get {
                return ResourceManager.GetString("ObjectiveCardName_OccupyTheSeatOfTheEmpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Vast Territories.
        /// </summary>
        internal static string ObjectiveCardName_PatrolVastTerritories {
            get {
                return ResourceManager.GetString("ObjectiveCardName_PatrolVastTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate The Outer Rim.
        /// </summary>
        internal static string ObjectiveCardName_PopulateTheOuterRim {
            get {
                return ResourceManager.GetString("ObjectiveCardName_PopulateTheOuterRim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce En Masse.
        /// </summary>
        internal static string ObjectiveCardName_ProduceEnMasse {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ProduceEnMasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect The Border.
        /// </summary>
        internal static string ObjectiveCardName_ProtectTheBorder {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ProtectTheBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prove Endurance.
        /// </summary>
        internal static string ObjectiveCardName_ProveEndurance {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ProveEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Boundaries.
        /// </summary>
        internal static string ObjectiveCardName_PushBoundaries {
            get {
                return ResourceManager.GetString("ObjectiveCardName_PushBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise A Fleet.
        /// </summary>
        internal static string ObjectiveCardName_RaiseAFleet {
            get {
                return ResourceManager.GetString("ObjectiveCardName_RaiseAFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reclaim Ancient Monuments.
        /// </summary>
        internal static string ObjectiveCardName_ReclaimAncientMonuments {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ReclaimAncientMonuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolutionize Warfare.
        /// </summary>
        internal static string ObjectiveCardName_RevolutionizeWarfare {
            get {
                return ResourceManager.GetString("ObjectiveCardName_RevolutionizeWarfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Distant Lands.
        /// </summary>
        internal static string ObjectiveCardName_RuleDistantLands {
            get {
                return ResourceManager.GetString("ObjectiveCardName_RuleDistantLands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seize An Icon.
        /// </summary>
        internal static string ObjectiveCardName_SeizeAnIcon {
            get {
                return ResourceManager.GetString("ObjectiveCardName_SeizeAnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark A Rebellion.
        /// </summary>
        internal static string ObjectiveCardName_SparkARebellion {
            get {
                return ResourceManager.GetString("ObjectiveCardName_SparkARebellion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake Your Claim.
        /// </summary>
        internal static string ObjectiveCardName_StakeYourClaim {
            get {
                return ResourceManager.GetString("ObjectiveCardName_StakeYourClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strengthen Bonds.
        /// </summary>
        internal static string ObjectiveCardName_StrengthenBonds {
            get {
                return ResourceManager.GetString("ObjectiveCardName_StrengthenBonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdue The Galaxy.
        /// </summary>
        internal static string ObjectiveCardName_SubdueTheGalaxy {
            get {
                return ResourceManager.GetString("ObjectiveCardName_SubdueTheGalaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sway The Council.
        /// </summary>
        internal static string ObjectiveCardName_SwayTheCouncil {
            get {
                return ResourceManager.GetString("ObjectiveCardName_SwayTheCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threaten Enemies.
        /// </summary>
        internal static string ObjectiveCardName_ThreatenEnemies {
            get {
                return ResourceManager.GetString("ObjectiveCardName_ThreatenEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Their Fleets To Dust.
        /// </summary>
        internal static string ObjectiveCardName_TurnTheirFleetsToDust {
            get {
                return ResourceManager.GetString("ObjectiveCardName_TurnTheirFleetsToDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Their Fleets To Dust  Ω.
        /// </summary>
        internal static string ObjectiveCardName_TurnTheirFleetsToDustOmega {
            get {
                return ResourceManager.GetString("ObjectiveCardName_TurnTheirFleetsToDustOmega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unify The Colonies.
        /// </summary>
        internal static string ObjectiveCardName_UnifyTheColonies {
            get {
                return ResourceManager.GetString("ObjectiveCardName_UnifyTheColonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unveil Flagship.
        /// </summary>
        internal static string ObjectiveCardName_UnveilFlagship {
            get {
                return ResourceManager.GetString("ObjectiveCardName_UnveilFlagship", resourceCulture);
            }
        }
    }
}
