//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilightImperiumUltimate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilightImperiumUltimate.Web.Resources.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/.
        /// </summary>
        public static string ApiPath_Cards {
            get {
                return ResourceManager.GetString("ApiPath_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/drafts/colors.
        /// </summary>
        public static string ApiPath_ColorDraft {
            get {
                return ResourceManager.GetString("ApiPath_ColorDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/drafts/factions.
        /// </summary>
        public static string ApiPath_FactionDraft {
            get {
                return ResourceManager.GetString("ApiPath_FactionDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/factions.
        /// </summary>
        public static string ApiPath_Factions {
            get {
                return ResourceManager.GetString("ApiPath_Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/factions/1.
        /// </summary>
        public static string ApiPath_FirstFaction {
            get {
                return ResourceManager.GetString("ApiPath_FirstFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/mapgenerators.
        /// </summary>
        public static string ApiPath_MapDraft {
            get {
                return ResourceManager.GetString("ApiPath_MapDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/news.
        /// </summary>
        public static string ApiPath_News {
            get {
                return ResourceManager.GetString("ApiPath_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/galaxy/tiles.
        /// </summary>
        public static string ApiPath_SystemTiles {
            get {
                return ResourceManager.GetString("ApiPath_SystemTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwilightImperiumUltimate.Web.Resources.FactionsInfo.
        /// </summary>
        public static string ResourceNamespace_FactionInfo {
            get {
                return ResourceManager.GetString("ResourceNamespace_FactionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwilightImperiumUltimate.Web.Resources.Strings.
        /// </summary>
        public static string ResourceNamespace_Strings {
            get {
                return ResourceManager.GetString("ResourceNamespace_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /resources/images/shared/cardgenerator.
        /// </summary>
        public static string ResourcePath_CardGeneratorPath {
            get {
                return ResourceManager.GetString("ResourcePath_CardGeneratorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\cardicons.
        /// </summary>
        public static string ResourcePath_CardTypeIconPath {
            get {
                return ResourceManager.GetString("ResourcePath_CardTypeIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\complexity.
        /// </summary>
        public static string ResourcePath_ComplexityPath {
            get {
                return ResourceManager.GetString("ResourcePath_ComplexityPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\cultures.
        /// </summary>
        public static string ResourcePath_CulturePath {
            get {
                return ResourceManager.GetString("ResourcePath_CulturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\factionicons.
        /// </summary>
        public static string ResourcePath_FactionIconPath {
            get {
                return ResourceManager.GetString("ResourcePath_FactionIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\factionimages.
        /// </summary>
        public static string ResourcePath_FactionImagePath {
            get {
                return ResourceManager.GetString("ResourcePath_FactionImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\factionimages.
        /// </summary>
        public static string ResourcePath_FactionSheetPath {
            get {
                return ResourceManager.GetString("ResourcePath_FactionSheetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\tiles\large.
        /// </summary>
        public static string ResourcePath_LargeTilePath {
            get {
                return ResourceManager.GetString("ResourcePath_LargeTilePath", resourceCulture);
            }
        }
    }
}
