//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilightImperiumUltimate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilightImperiumUltimate.Web.Resources.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmEmail.
        /// </summary>
        public static string ApiPath_AccountConfirmEmail {
            get {
                return ResourceManager.GetString("ApiPath_AccountConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login?useCookies=false&amp;useSessionCookies=false.
        /// </summary>
        public static string ApiPath_AccountLogin {
            get {
                return ResourceManager.GetString("ApiPath_AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string ApiPath_AccountRefreshToken {
            get {
                return ResourceManager.GetString("ApiPath_AccountRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string ApiPath_AccountRegister {
            get {
                return ResourceManager.GetString("ApiPath_AccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/action.
        /// </summary>
        public static string ApiPath_ActionCards {
            get {
                return ResourceManager.GetString("ApiPath_ActionCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/agenda.
        /// </summary>
        public static string ApiPath_AgendaCards {
            get {
                return ResourceManager.GetString("ApiPath_AgendaCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/.
        /// </summary>
        public static string ApiPath_Cards {
            get {
                return ResourceManager.GetString("ApiPath_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/drafts/colors.
        /// </summary>
        public static string ApiPath_ColorDraft {
            get {
                return ResourceManager.GetString("ApiPath_ColorDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/exploration.
        /// </summary>
        public static string ApiPath_ExplorationCards {
            get {
                return ResourceManager.GetString("ApiPath_ExplorationCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/drafts/factions.
        /// </summary>
        public static string ApiPath_FactionDraft {
            get {
                return ResourceManager.GetString("ApiPath_FactionDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/factions.
        /// </summary>
        public static string ApiPath_Factions {
            get {
                return ResourceManager.GetString("ApiPath_Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/factions/1.
        /// </summary>
        public static string ApiPath_FirstFaction {
            get {
                return ResourceManager.GetString("ApiPath_FirstFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forgotPassword.
        /// </summary>
        public static string ApiPath_ForgotPassword {
            get {
                return ResourceManager.GetString("ApiPath_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/frontier.
        /// </summary>
        public static string ApiPath_FrontierCards {
            get {
                return ResourceManager.GetString("ApiPath_FrontierCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/map-generators/generate-map.
        /// </summary>
        public static string ApiPath_GenerateMap {
            get {
                return ResourceManager.GetString("ApiPath_GenerateMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage/info.
        /// </summary>
        public static string ApiPath_ManageInfo {
            get {
                return ResourceManager.GetString("ApiPath_ManageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/news.
        /// </summary>
        public static string ApiPath_News {
            get {
                return ResourceManager.GetString("ApiPath_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/objective.
        /// </summary>
        public static string ApiPath_ObjectiveCards {
            get {
                return ResourceManager.GetString("ApiPath_ObjectiveCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/galaxy/planets.
        /// </summary>
        public static string ApiPath_Planets {
            get {
                return ResourceManager.GetString("ApiPath_Planets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/promissory-note.
        /// </summary>
        public static string ApiPath_PromissoryNoteCards {
            get {
                return ResourceManager.GetString("ApiPath_PromissoryNoteCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/promissory-note.
        /// </summary>
        public static string ApiPath_PromissoryNotes {
            get {
                return ResourceManager.GetString("ApiPath_PromissoryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/relic.
        /// </summary>
        public static string ApiPath_RelicCards {
            get {
                return ResourceManager.GetString("ApiPath_RelicCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resendConfirmationEmail.
        /// </summary>
        public static string ApiPath_ResendConfirmationEmail {
            get {
                return ResourceManager.GetString("ApiPath_ResendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resetPassword.
        /// </summary>
        public static string ApiPath_ResetPassword {
            get {
                return ResourceManager.GetString("ApiPath_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/rules.
        /// </summary>
        public static string ApiPath_Rules {
            get {
                return ResourceManager.GetString("ApiPath_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/secret.
        /// </summary>
        public static string ApiPath_SecretObjectiveCards {
            get {
                return ResourceManager.GetString("ApiPath_SecretObjectiveCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/stage-one-objective.
        /// </summary>
        public static string ApiPath_StageOneObjectiveCards {
            get {
                return ResourceManager.GetString("ApiPath_StageOneObjectiveCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/stage-two-objective.
        /// </summary>
        public static string ApiPath_StageTwoObjectiveCards {
            get {
                return ResourceManager.GetString("ApiPath_StageTwoObjectiveCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cards/strategy.
        /// </summary>
        public static string ApiPath_StrategyCards {
            get {
                return ResourceManager.GetString("ApiPath_StrategyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/galaxy/system-tiles.
        /// </summary>
        public static string ApiPath_SystemTiles {
            get {
                return ResourceManager.GetString("ApiPath_SystemTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/technologies.
        /// </summary>
        public static string ApiPath_Technologies {
            get {
                return ResourceManager.GetString("ApiPath_Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/user/byemail.
        /// </summary>
        public static string ApiPath_UserByEmail {
            get {
                return ResourceManager.GetString("ApiPath_UserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/user.
        /// </summary>
        public static string ApiPath_Users {
            get {
                return ResourceManager.GetString("ApiPath_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/user/update.
        /// </summary>
        public static string ApiPath_UserUpdate {
            get {
                return ResourceManager.GetString("ApiPath_UserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwilightImperiumUltimate.Web.Resources.FactionsInfo.
        /// </summary>
        public static string ResourceNamespace_FactionInfo {
            get {
                return ResourceManager.GetString("ResourceNamespace_FactionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwilightImperiumUltimate.Web.Resources.Rules.
        /// </summary>
        public static string ResourceNamespace_Rules {
            get {
                return ResourceManager.GetString("ResourceNamespace_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwilightImperiumUltimate.Web.Resources.Strings.
        /// </summary>
        public static string ResourceNamespace_Strings {
            get {
                return ResourceManager.GetString("ResourceNamespace_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string ResourcePath_ActionCard {
            get {
                return ResourceManager.GetString("ResourcePath_ActionCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agenda.
        /// </summary>
        public static string ResourcePath_AgendaCard {
            get {
                return ResourceManager.GetString("ResourcePath_AgendaCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /resources/images/{language}/cardgenerator.
        /// </summary>
        public static string ResourcePath_CardGeneratorPath {
            get {
                return ResourceManager.GetString("ResourcePath_CardGeneratorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\cardicons.
        /// </summary>
        public static string ResourcePath_CardTypeIconPath {
            get {
                return ResourceManager.GetString("ResourcePath_CardTypeIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\complexity.
        /// </summary>
        public static string ResourcePath_ComplexityPath {
            get {
                return ResourceManager.GetString("ResourcePath_ComplexityPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\cultures.
        /// </summary>
        public static string ResourcePath_CulturePath {
            get {
                return ResourceManager.GetString("ResourcePath_CulturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exploration.
        /// </summary>
        public static string ResourcePath_ExplorationCard {
            get {
                return ResourceManager.GetString("ResourcePath_ExplorationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\{language}\leaders.
        /// </summary>
        public static string ResourcePath_FactionComponentsPath {
            get {
                return ResourceManager.GetString("ResourcePath_FactionComponentsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\factionicons.
        /// </summary>
        public static string ResourcePath_FactionIconPath {
            get {
                return ResourceManager.GetString("ResourcePath_FactionIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\factionimages.
        /// </summary>
        public static string ResourcePath_FactionImagePath {
            get {
                return ResourceManager.GetString("ResourcePath_FactionImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\factionimages.
        /// </summary>
        public static string ResourcePath_FactionSheetPath {
            get {
                return ResourceManager.GetString("ResourcePath_FactionSheetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frontier.
        /// </summary>
        public static string ResourcePath_FrontierCard {
            get {
                return ResourceManager.GetString("ResourcePath_FrontierCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\icons.
        /// </summary>
        public static string ResourcePath_IconPath {
            get {
                return ResourceManager.GetString("ResourcePath_IconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\tiles\large.
        /// </summary>
        public static string ResourcePath_LargeTilePath {
            get {
                return ResourceManager.GetString("ResourcePath_LargeTilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objective/secret.
        /// </summary>
        public static string ResourcePath_ObjectiveSecret {
            get {
                return ResourceManager.GetString("ResourcePath_ObjectiveSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objective/stageone.
        /// </summary>
        public static string ResourcePath_ObjectiveStageOne {
            get {
                return ResourceManager.GetString("ResourcePath_ObjectiveStageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objective/stagetwo.
        /// </summary>
        public static string ResourcePath_ObjectiveStageTwo {
            get {
                return ResourceManager.GetString("ResourcePath_ObjectiveStageTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\{language}\planets.
        /// </summary>
        public static string ResourcePath_PlanetImagePath {
            get {
                return ResourceManager.GetString("ResourcePath_PlanetImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promissory.
        /// </summary>
        public static string ResourcePath_PromissoryCard {
            get {
                return ResourceManager.GetString("ResourcePath_PromissoryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\{language}\cards\promissary.
        /// </summary>
        public static string ResourcePath_PromissoryNotePath {
            get {
                return ResourceManager.GetString("ResourcePath_PromissoryNotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relic.
        /// </summary>
        public static string ResourcePath_RelicCard {
            get {
                return ResourceManager.GetString("ResourcePath_RelicCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strategy.
        /// </summary>
        public static string ResourcePath_StrategyCard {
            get {
                return ResourceManager.GetString("ResourcePath_StrategyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\technologies.
        /// </summary>
        public static string ResourcePath_TechnologyIconPath {
            get {
                return ResourceManager.GetString("ResourcePath_TechnologyIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\{language}\technologies.
        /// </summary>
        public static string ResourcePath_TechnologyImagePath {
            get {
                return ResourceManager.GetString("ResourcePath_TechnologyImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\textures.
        /// </summary>
        public static string ResourcePath_TexturePath {
            get {
                return ResourceManager.GetString("ResourcePath_TexturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\units.
        /// </summary>
        public static string ResourcePath_UnitImagePath {
            get {
                return ResourceManager.GetString("ResourcePath_UnitImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \resources\images\shared\websites.
        /// </summary>
        public static string ResourcePath_WebsitePreviewPath {
            get {
                return ResourceManager.GetString("ResourcePath_WebsitePreviewPath", resourceCulture);
            }
        }
    }
}
