//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilightImperiumUltimate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilightImperiumUltimate.Web.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        public static string BackSlash {
            get {
                return ResourceManager.GetString("BackSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to culture.
        /// </summary>
        public static string CultureKey {
            get {
                return ResourceManager.GetString("CultureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs-CZ.
        /// </summary>
        public static string CzechCulture {
            get {
                return ResourceManager.GetString("CzechCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\.
        /// </summary>
        public static string DoubleBackslash {
            get {
                return ResourceManager.GetString("DoubleBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string EnglishCulture {
            get {
                return ResourceManager.GetString("EnglishCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        public static string FileExtensionPng {
            get {
                return ResourceManager.GetString("FileExtensionPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string ForwardSlash {
            get {
                return ResourceManager.GetString("ForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {language}.
        /// </summary>
        public static string LanguagePlaceholder {
            get {
                return ResourceManager.GetString("LanguagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret.
        /// </summary>
        public static string ObjectiveCardSecret {
            get {
                return ResourceManager.GetString("ObjectiveCardSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stageoneobjective.
        /// </summary>
        public static string ObjectiveCardStageOne {
            get {
                return ResourceManager.GetString("ObjectiveCardStageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stagetwoobjective.
        /// </summary>
        public static string ObjectiveCardStageTwo {
            get {
                return ResourceManager.GetString("ObjectiveCardStageTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Page_About {
            get {
                return ResourceManager.GetString("Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Calculator.
        /// </summary>
        public static string Page_BattleCalculator {
            get {
                return ResourceManager.GetString("Page_BattleCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Page_Cards {
            get {
                return ResourceManager.GetString("Page_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Draft.
        /// </summary>
        public static string Page_ColorDraft {
            get {
                return ResourceManager.GetString("Page_ColorDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Page_Draft {
            get {
                return ResourceManager.GetString("Page_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction Draft.
        /// </summary>
        public static string Page_FactionDraft {
            get {
                return ResourceManager.GetString("Page_FactionDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factions.
        /// </summary>
        public static string Page_Factions {
            get {
                return ResourceManager.GetString("Page_Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq.
        /// </summary>
        public static string Page_Faq {
            get {
                return ResourceManager.GetString("Page_Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Page_Game {
            get {
                return ResourceManager.GetString("Page_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Page_Rules {
            get {
                return ResourceManager.GetString("Page_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies.
        /// </summary>
        public static string Page_Technologies {
            get {
                return ResourceManager.GetString("Page_Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Page_Tools {
            get {
                return ResourceManager.GetString("Page_Tools", resourceCulture);
            }
        }
    }
}
