//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilightImperiumUltimate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilightImperiumUltimate.Web.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string ActionCard {
            get {
                return ResourceManager.GetString("ActionCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agenda.
        /// </summary>
        public static string AgendaCard {
            get {
                return ResourceManager.GetString("AgendaCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        public static string BackSlash {
            get {
                return ResourceManager.GetString("BackSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8249;.
        /// </summary>
        public static string ButtonLeftArrow {
            get {
                return ResourceManager.GetString("ButtonLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8250;.
        /// </summary>
        public static string ButtonRightArrow {
            get {
                return ResourceManager.GetString("ButtonRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Card.
        /// </summary>
        public static string CardGenerationType_Action {
            get {
                return ResourceManager.GetString("CardGenerationType_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda Card (Directive).
        /// </summary>
        public static string CardGenerationType_AgendaDirective {
            get {
                return ResourceManager.GetString("CardGenerationType_AgendaDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda Card (Law).
        /// </summary>
        public static string CardGenerationType_AgendaLaw {
            get {
                return ResourceManager.GetString("CardGenerationType_AgendaLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective Card (Stage One).
        /// </summary>
        public static string CardGenerationType_PublicObjectiveStageOne {
            get {
                return ResourceManager.GetString("CardGenerationType_PublicObjectiveStageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective Card (Stage Two).
        /// </summary>
        public static string CardGenerationType_PublicObjectiveStageTwo {
            get {
                return ResourceManager.GetString("CardGenerationType_PublicObjectiveStageTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Card (Action).
        /// </summary>
        public static string CardGenerationType_SecretObjectiveActionPhase {
            get {
                return ResourceManager.GetString("CardGenerationType_SecretObjectiveActionPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Card (Agenda).
        /// </summary>
        public static string CardGenerationType_SecretObjectiveAgendaPhase {
            get {
                return ResourceManager.GetString("CardGenerationType_SecretObjectiveAgendaPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Card (Status).
        /// </summary>
        public static string CardGenerationType_SecretObjectiveStatusPhase {
            get {
                return ResourceManager.GetString("CardGenerationType_SecretObjectiveStatusPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string CardTitle_Action {
            get {
                return ResourceManager.GetString("CardTitle_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string CardTitle_Agenda {
            get {
                return ResourceManager.GetString("CardTitle_Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration.
        /// </summary>
        public static string CardTitle_Exploration {
            get {
                return ResourceManager.GetString("CardTitle_Exploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontier.
        /// </summary>
        public static string CardTitle_Frontier {
            get {
                return ResourceManager.GetString("CardTitle_Frontier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective One.
        /// </summary>
        public static string CardTitle_ObjectiveOne {
            get {
                return ResourceManager.GetString("CardTitle_ObjectiveOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onjective Two.
        /// </summary>
        public static string CardTitle_ObjectiveTwo {
            get {
                return ResourceManager.GetString("CardTitle_ObjectiveTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        public static string CardTitle_Relic {
            get {
                return ResourceManager.GetString("CardTitle_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string CardTitle_Secret {
            get {
                return ResourceManager.GetString("CardTitle_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string CardTitle_Strategy {
            get {
                return ResourceManager.GetString("CardTitle_Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...Picking colors....
        /// </summary>
        public static string ColorPcikerButton_Drafting {
            get {
                return ResourceManager.GetString("ColorPcikerButton_Drafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select factions from the row above).
        /// </summary>
        public static string ColorPicker_HelpText {
            get {
                return ResourceManager.GetString("ColorPicker_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string ColorPicker_Title {
            get {
                return ResourceManager.GetString("ColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick colors.
        /// </summary>
        public static string ColorPickerButton_DraftReady {
            get {
                return ResourceManager.GetString("ColorPickerButton_DraftReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough colors.
        /// </summary>
        public static string ColorPickerButton_NotEnoughColors {
            get {
                return ResourceManager.GetString("ColorPickerButton_NotEnoughColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlazorCulture.
        /// </summary>
        public static string CultureKey {
            get {
                return ResourceManager.GetString("CultureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs-CZ.
        /// </summary>
        public static string CzechCulture {
            get {
                return ResourceManager.GetString("CzechCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\.
        /// </summary>
        public static string DoubleBackslash {
            get {
                return ResourceManager.GetString("DoubleBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough factions.
        /// </summary>
        public static string DraftButton_BanToMany {
            get {
                return ResourceManager.GetString("DraftButton_BanToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft colors.
        /// </summary>
        public static string DraftButton_DraftColors {
            get {
                return ResourceManager.GetString("DraftButton_DraftColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...Drafting....
        /// </summary>
        public static string DraftButton_DraftInProgress {
            get {
                return ResourceManager.GetString("DraftButton_DraftInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string DraftButton_DraftReady {
            get {
                return ResourceManager.GetString("DraftButton_DraftReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Draft.
        /// </summary>
        public static string DraftButton_Reset {
            get {
                return ResourceManager.GetString("DraftButton_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset colors.
        /// </summary>
        public static string DraftButton_ResetBannedColors {
            get {
                return ResourceManager.GetString("DraftButton_ResetBannedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset bans.
        /// </summary>
        public static string DraftButton_ResetBans {
            get {
                return ResourceManager.GetString("DraftButton_ResetBans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset factions.
        /// </summary>
        public static string DraftButton_ResetSelectedFactions {
            get {
                return ResourceManager.GetString("DraftButton_ResetSelectedFactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To many bans for a draft to be possible. Please reduce the number of bans or decrease the number of factions drafted per player or number of players..
        /// </summary>
        public static string DraftText_DraftNotPossible {
            get {
                return ResourceManager.GetString("DraftText_DraftNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of factions per player:.
        /// </summary>
        public static string DraftText_NumberOfFactions {
            get {
                return ResourceManager.GetString("DraftText_NumberOfFactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of players:.
        /// </summary>
        public static string DraftText_NumberOfPlayers {
            get {
                return ResourceManager.GetString("DraftText_NumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string EnglishCulture {
            get {
                return ResourceManager.GetString("EnglishCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exploration.
        /// </summary>
        public static string ExplorationCard {
            get {
                return ResourceManager.GetString("ExplorationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (To ban a faction, click on the faction icon above).
        /// </summary>
        public static string FactionDraft_BanHelp {
            get {
                return ResourceManager.GetString("FactionDraft_BanHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction Draft.
        /// </summary>
        public static string FactionDraft_Title {
            get {
                return ResourceManager.GetString("FactionDraft_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factions:.
        /// </summary>
        public static string Factions {
            get {
                return ResourceManager.GetString("Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactionSheet.
        /// </summary>
        public static string FactionSheet {
            get {
                return ResourceManager.GetString("FactionSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactionSheetBack.
        /// </summary>
        public static string FactionSheetBack {
            get {
                return ResourceManager.GetString("FactionSheetBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        public static string FileExtensionPng {
            get {
                return ResourceManager.GetString("FileExtensionPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .webp.
        /// </summary>
        public static string FileExtensionWebp {
            get {
                return ResourceManager.GetString("FileExtensionWebp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string ForwardSlash {
            get {
                return ResourceManager.GetString("ForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frontier.
        /// </summary>
        public static string FrontierCard {
            get {
                return ResourceManager.GetString("FrontierCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {language}.
        /// </summary>
        public static string LanguagePlaceholder {
            get {
                return ResourceManager.GetString("LanguagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tiles.
        /// </summary>
        public static string MapGenerator_AllTiles {
            get {
                return ResourceManager.GetString("MapGenerator_AllTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Scale.
        /// </summary>
        public static string MapGenerator_MapScale {
            get {
                return ResourceManager.GetString("MapGenerator_MapScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused Tiles.
        /// </summary>
        public static string MapGenerator_UnusedTiles {
            get {
                return ResourceManager.GetString("MapGenerator_UnusedTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string MapTemplate_CustomMap {
            get {
                return ResourceManager.GetString("MapTemplate_CustomMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8P Large Map.
        /// </summary>
        public static string MapTemplate_LargeMapEightPlayers {
            get {
                return ResourceManager.GetString("MapTemplate_LargeMapEightPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6P Large Map.
        /// </summary>
        public static string MapTemplate_LargeMapSixPlayers {
            get {
                return ResourceManager.GetString("MapTemplate_LargeMapSixPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3P Manta Ray.
        /// </summary>
        public static string MapTemplate_MantaRayMapThreePlayers {
            get {
                return ResourceManager.GetString("MapTemplate_MantaRayMapThreePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4P Medium Map.
        /// </summary>
        public static string MapTemplate_MediumMapFourPlayers {
            get {
                return ResourceManager.GetString("MapTemplate_MediumMapFourPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6P Medium Map.
        /// </summary>
        public static string MapTemplate_MediumMapSixPlayers {
            get {
                return ResourceManager.GetString("MapTemplate_MediumMapSixPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3P Small Map Alternate.
        /// </summary>
        public static string MapTemplate_SmallMapAlternateThreePlayers {
            get {
                return ResourceManager.GetString("MapTemplate_SmallMapAlternateThreePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3P Small Map.
        /// </summary>
        public static string MapTemplate_SmallMapThreePlayers {
            get {
                return ResourceManager.GetString("MapTemplate_SmallMapThreePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3P Snowflake.
        /// </summary>
        public static string MapTemplate_SnowflakeMapThreePlayers {
            get {
                return ResourceManager.GetString("MapTemplate_SnowflakeMapThreePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3P Triangle.
        /// </summary>
        public static string MapTemplate_TriangleMapThreePlayers {
            get {
                return ResourceManager.GetString("MapTemplate_TriangleMapThreePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3P Triangle Narrow.
        /// </summary>
        public static string MapTemplate_TriangleNarrowMapThreePlayers {
            get {
                return ResourceManager.GetString("MapTemplate_TriangleNarrowMapThreePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3P Trident.
        /// </summary>
        public static string MapTemplate_TridentMapThreePlayers {
            get {
                return ResourceManager.GetString("MapTemplate_TridentMapThreePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret.
        /// </summary>
        public static string ObjectiveCardSecret {
            get {
                return ResourceManager.GetString("ObjectiveCardSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stageoneobjective.
        /// </summary>
        public static string ObjectiveCardStageOne {
            get {
                return ResourceManager.GetString("ObjectiveCardStageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stagetwoobjective.
        /// </summary>
        public static string ObjectiveCardStageTwo {
            get {
                return ResourceManager.GetString("ObjectiveCardStageTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Page_About {
            get {
                return ResourceManager.GetString("Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Calculator.
        /// </summary>
        public static string Page_BattleCalculator {
            get {
                return ResourceManager.GetString("Page_BattleCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Generator.
        /// </summary>
        public static string Page_CardGenerator {
            get {
                return ResourceManager.GetString("Page_CardGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Page_Cards {
            get {
                return ResourceManager.GetString("Page_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string Page_ColorPicker {
            get {
                return ResourceManager.GetString("Page_ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Page_Draft {
            get {
                return ResourceManager.GetString("Page_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction Draft.
        /// </summary>
        public static string Page_FactionDraft {
            get {
                return ResourceManager.GetString("Page_FactionDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factions.
        /// </summary>
        public static string Page_Factions {
            get {
                return ResourceManager.GetString("Page_Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq.
        /// </summary>
        public static string Page_Faq {
            get {
                return ResourceManager.GetString("Page_Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Page_Game {
            get {
                return ResourceManager.GetString("Page_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Generator.
        /// </summary>
        public static string Page_MapGenerator {
            get {
                return ResourceManager.GetString("Page_MapGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Page_Rules {
            get {
                return ResourceManager.GetString("Page_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies.
        /// </summary>
        public static string Page_Technologies {
            get {
                return ResourceManager.GetString("Page_Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Page_Tools {
            get {
                return ResourceManager.GetString("Page_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PlacementStyle_Home {
            get {
                return ResourceManager.GetString("PlacementStyle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial.
        /// </summary>
        public static string PlacementStyle_Initial {
            get {
                return ResourceManager.GetString("PlacementStyle_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string PlacementStyle_Random {
            get {
                return ResourceManager.GetString("PlacementStyle_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice.
        /// </summary>
        public static string PlacementStyle_Slice {
            get {
                return ResourceManager.GetString("PlacementStyle_Slice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}.
        /// </summary>
        public static string PlayerNamePlaceholder {
            get {
                return ResourceManager.GetString("PlayerNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relic.
        /// </summary>
        public static string RelicCard {
            get {
                return ResourceManager.GetString("RelicCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strategy.
        /// </summary>
        public static string StrategyCard {
            get {
                return ResourceManager.GetString("StrategyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SystemTileOverlay_Id {
            get {
                return ResourceManager.GetString("SystemTileOverlay_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influence.
        /// </summary>
        public static string SystemTileOverlay_Influence {
            get {
                return ResourceManager.GetString("SystemTileOverlay_Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SystemTileOverlay_None {
            get {
                return ResourceManager.GetString("SystemTileOverlay_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string SystemTileOverlay_Resources {
            get {
                return ResourceManager.GetString("SystemTileOverlay_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource and Influence.
        /// </summary>
        public static string SystemTileOverlay_ResourcesAndInfluence {
            get {
                return ResourceManager.GetString("SystemTileOverlay_ResourcesAndInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SystemTileTypeFilter_All {
            get {
                return ResourceManager.GetString("SystemTileTypeFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Tiles.
        /// </summary>
        public static string SystemTileTypeFilter_BlueTiles {
            get {
                return ResourceManager.GetString("SystemTileTypeFilter_BlueTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Systems.
        /// </summary>
        public static string SystemTileTypeFilter_HomeSystems {
            get {
                return ResourceManager.GetString("SystemTileTypeFilter_HomeSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlanes.
        /// </summary>
        public static string SystemTileTypeFilter_Hyperlanes {
            get {
                return ResourceManager.GetString("SystemTileTypeFilter_Hyperlanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mecatol Rex.
        /// </summary>
        public static string SystemTileTypeFilter_MecatolRex {
            get {
                return ResourceManager.GetString("SystemTileTypeFilter_MecatolRex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Tiles.
        /// </summary>
        public static string SystemTileTypeFilter_RedTiles {
            get {
                return ResourceManager.GetString("SystemTileTypeFilter_RedTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string SystemTileTypeFilter_Unused {
            get {
                return ResourceManager.GetString("SystemTileTypeFilter_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string SystemWeight_Balanced {
            get {
                return ResourceManager.GetString("SystemWeight_Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influence.
        /// </summary>
        public static string SystemWeight_Influence {
            get {
                return ResourceManager.GetString("SystemWeight_Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string SystemWeight_Random {
            get {
                return ResourceManager.GetString("SystemWeight_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string SystemWeight_Resources {
            get {
                return ResourceManager.GetString("SystemWeight_Resources", resourceCulture);
            }
        }
    }
}
