//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilightImperiumUltimate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilightImperiumUltimate.Web.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match..
        /// </summary>
        public static string Register_ConfirmPasswordMatch {
            get {
                return ResourceManager.GetString("Register_ConfirmPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email is required..
        /// </summary>
        public static string Register_EmailNotValid {
            get {
                return ResourceManager.GetString("Register_EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Register_EmptyEmail {
            get {
                return ResourceManager.GetString("Register_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Register_EmptyPassword {
            get {
                return ResourceManager.GetString("Register_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit..
        /// </summary>
        public static string Register_PasswordOneDigit {
            get {
                return ResourceManager.GetString("Register_PasswordOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        public static string Register_PasswordOneLowerLetter {
            get {
                return ResourceManager.GetString("Register_PasswordOneLowerLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one non-alphanumeric character..
        /// </summary>
        public static string Register_PasswordOneNonAlphaNumeric {
            get {
                return ResourceManager.GetString("Register_PasswordOneNonAlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string Register_PasswordOneUpperLetter {
            get {
                return ResourceManager.GetString("Register_PasswordOneUpperLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long..
        /// </summary>
        public static string Register_PasswordSixCharacters {
            get {
                return ResourceManager.GetString("Register_PasswordSixCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match..
        /// </summary>
        public static string ResetPassword__ConfirmPasswordMatch {
            get {
                return ResourceManager.GetString("ResetPassword__ConfirmPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string ResetPassword_EmptyPassword {
            get {
                return ResourceManager.GetString("ResetPassword_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset code cannot be empty!.
        /// </summary>
        public static string ResetPassword_EmptyResetCode {
            get {
                return ResourceManager.GetString("ResetPassword_EmptyResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit..
        /// </summary>
        public static string ResetPassword_PasswordOneDigit {
            get {
                return ResourceManager.GetString("ResetPassword_PasswordOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        public static string ResetPassword_PasswordOneLowerLetter {
            get {
                return ResourceManager.GetString("ResetPassword_PasswordOneLowerLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one non-alphanumeric character..
        /// </summary>
        public static string ResetPassword_PasswordOneNonAlphaNumeric {
            get {
                return ResourceManager.GetString("ResetPassword_PasswordOneNonAlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string ResetPassword_PasswordOneUpperLetter {
            get {
                return ResourceManager.GetString("ResetPassword_PasswordOneUpperLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long..
        /// </summary>
        public static string ResetPassword_PasswordSixCharacters {
            get {
                return ResourceManager.GetString("ResetPassword_PasswordSixCharacters", resourceCulture);
            }
        }
    }
}
