namespace TwilightImperiumUltimate.Web.Enums;

public enum MapTemplateFilter
{
    CustomMap,
    TwoPlayersMediumMap,
    ThreePlayersSmallMap,
    ThreePlayersSmallAlternateMap,
    ThreePlayersMediumHyperlineMap,
    ThreePlayersMediumTriangleMap,
    ThreePlayersMediumTriangleNarrowMap,
    ThreePlayersMediumSnowflakeMap,
    ThreePlayersMediumMantaRayMap,
    ThreePlayersMediumTridentMap,
    ThreePlayersMediumRexMap,
    FourPlayersMediumMap,
    FourPlayersMediumHyperlineMap,
    FourPlayersMediumHorizontalMap,
    FourPlayersMediumVerticalMap,
    FourPlayersMediumGapsMap,
    FourPlayersMediumWarpMap,
    FourPlayersMediumMiniWarpMap,
    FourPlayersMediumDoubleWarpMap,
    FivePlayersMediumMap,
    FivePlayersMediumHyperlineMap,
    FivePlayersMediumDiamondMap,
    FivePlayersLargeFlatMap,
    SixPlayersMediumMap,
    SixPlayersMediumSpiralMap,
    SixPlayersLargeMap,
    SevenPlayersLargeHyperlineMap,
    SevenPlayersLargeWarpMap,
    EightPlayersLargeMap,
    EightPlayersLargeWarpMap,
    All,
}
